env:
  Rapid_key: ${{ secrets.Rapid_key }}
 
name: create-map
on: push
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./get_client_country.sh
         ./get_client_country.sh
         chmod +x ./lang.sh
         ./lang.sh
         chmod +x ./message.sh
         ./message.sh
      shell: bash
